{"name":"Template - SharePoint Folder - Excel","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-11-12T11:13:12.405934+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"skipAutomaticHeaderAndTypeDetection":false,"queriesMetadata":{"Files":{"queryId":"4dbd3c6a-733a-42ee-9b2e-b5611aed45f5","queryName":"Files","loadEnabled":true},"SP_Url":{"queryId":"417137de-87ca-4ab7-a8e8-34aa033d0a3c","queryName":"SP_Url","queryGroupId":"55928464-d7b1-40f0-889a-6e1de842812b"},"SP_Folder":{"queryId":"7668fd5b-2405-4aa4-9794-ad24899b1c42","queryName":"SP_Folder","queryGroupId":"55928464-d7b1-40f0-889a-6e1de842812b"}},"document":"section Section1;\r\nshared Files = let\r\n  Site = Text.Replace(SP_Url, \"https://beazley.sharepoint.com\", \"\"),\r\n  SiteApi = SP_Url & \"/_api/Web\",\r\n  FolderRelativePath = Text.Replace(SP_Folder, \"https://beazley.sharepoint.com/:f:/r\" & Site & \"/\", \"\"),\r\n  FolderPath = if Text.PositionOf(FolderRelativePath, \"?\") > 0 then Text.Range(FolderRelativePath, 0, Text.PositionOf(FolderRelativePath, \"?\")) else FolderRelativePath,\r\n  Source = Web.Contents(\r\n            SiteApi,\r\n            [\r\n                RelativePath = \"GetFolderByServerRelativeUrl('\" & Site & \"/\" & FolderPath & \"')/files\",\r\n                Headers=[\r\n                    \r\n                    Accept = \"application/json\"\r\n                ]\r\n            ]\r\n        ),\r\n  data = Json.Document(Source),\r\n  value = data[value],\r\n  #\"Converted to Table\" = Table.FromList(value, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\r\n  #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\", {\"Name\", \"ServerRelativeUrl\"}, {\"FileName\", \"ServerRelativeUrl\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded Column1\", {{\"ServerRelativeUrl\", type text}}),\r\n  AddFiles = Table.AddColumn(#\"Changed column type\", \"Files\", each Table.PromoteHeaders(Excel.Workbook(\r\n            Web.Contents(\r\n                SiteApi,\r\n                [\r\n                    RelativePath = \"GetFileByServerRelativeUrl('\"& [ServerRelativeUrl] & \"')/$value\",\r\n                    Headers=[\r\n                        Accept = \"application/json\"\r\n                    ]\r\n                ]\r\n            )\r\n        ){[Kind=\"Sheet\"]}[Data],[PromoteAllScalars=true]))\r\nin\r\n  AddFiles;\r\nshared SP_Url = let\r\n  SP_Url = \"https://beazley.sharepoint.com/sites/SolidOpsPBI-DEV\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  SP_Url;\r\nshared SP_Folder = let\r\n  SP_Folder = \"https://beazley.sharepoint.com/:f:/r/sites/SolidOpsPBI-DEV/PoC%20Excel/Sample%20files?csf=1&web=1&e=piBGYG\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  SP_Folder;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"55928464-d7b1-40f0-889a-6e1de842812b\",\"name\":\"Parameters\",\"description\":\"\",\"parentId\":null,\"order\":0}]"}],"entities":[{"$type":"LocalEntity","name":"Files","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Files.csv"},"attributes":[{"name":"FileName","dataType":"string"},{"name":"ServerRelativeUrl","dataType":"string"},{"name":"Files","dataType":"string"}]}]}