# This is a basic workflow to help you get started with Actions

name: 0 - Initialize PBI Project

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  initialize-project-pbi:
    if: ${{ github.repository }} != "template-powerbi-reports"
    uses: beazley/poc-gha-pbi/.github/workflows/init.yml@main
    secrets: inherit
  
