# This is a basic workflow to help you get started with Actions

name: 1 - Build Release PBI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-release-pbi:
    if: ${{ github.repository }} != "template-powerbi-reports"
    uses: ./.github/workflows/main.yml
    secrets: inherit
    
  validate-setup-pbi:
    #if: false #${{ github.repository }} != "template-powerbi-reports"
    if: ${{ startsWith(github.head_ref, 'init-proj-') }} && ${{ github.repository }} != "template-powerbi-reports"
    uses: ./.github/workflows/validate.yml
    secrets: inherit
 
  
    
