# This is a basic workflow to help you get started with Actions

name: 1 - Build Release PBI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-release-pbi:
    if: ${{ github.repository }} != "beazley/template-powerbi-reports" && ${{ github.event.head_commit.message }} != "Initial commit"
    uses: beazley/poc-gha-pbi/.github/workflows/main.yml@main
    secrets: inherit
    
  validate-setup-pbi:
    #if: false #${{ github.repository }} != "template-powerbi-reports"
    if: ${{ startsWith(github.head_ref, 'init-proj-') }} && ${{ github.repository }} != "beazley/template-powerbi-reports"
    uses: beazley/poc-gha-pbi/.github/workflows/validate.yml@main
    secrets: inherit
    
  initialize-project-pbi:
    if: ${{ github.repository }} != "beazley/template-powerbi-reports"  && ${{ startsWith(github.event.head_commit.message, 'Initial commit')
    uses: beazley/poc-gha-pbi/.github/workflows/init.yml@main
    secrets: inherit
 
  
    
